### ISSUE TITLE
Error with sall images

### ISSUE THREAD

**Issue by coma94** [eugeniashurko/fork-recognition#6]
> /home/et/ECOLE/M1/S2/image/fork-recognition/library/feature_extraction.py:33: RuntimeWarning: invalid value encountered in true_divide
>   norm_frequencies = frequencies / sum(frequencies)
> Traceback (most recent call last):
>   File "distance.py", line 29, in <module>
>     features2 = extract_features(p_image2)
>   File "/home/et/ECOLE/M1/S2/image/fork-recognition/library/feature_extraction.py", line 116, in extract_features
>     curv_hist = border_curvature_histogram(im)
>   File "/home/et/ECOLE/M1/S2/image/fork-recognition/library/feature_extraction.py", line 39, in border_curvature_histogram
>     im_dense_border = trace_border(image)
>   File "/home/et/ECOLE/M1/S2/image/fork-recognition/library/utils.py", line 93, in trace_border
>     current_pixel[0] + CONNECTIVITY_INC[connectivity][i][0],
> IndexError: invalid index to scalar variable.

**Comment by coma94** [comment]
Should be done.

**Comment by coma94** [comment]
Done ?
